name: dropdown_search
description: Simple, reactive and highly customizable Flutter Dropdown with a lot of features (search, adaptive platform, async/sync values, ...) with multi dropdown mode like menu, modal, dialog, bottomSheet and etc.
version: 6.0.1
homepage: https://github.com/salim-lachdhaf
git: https://github.com/salim-lachdhaf/dropdown_search
repository: https://github.com/salim-lachdhaf/dropdown_search

environment:
  sdk: ">=2.17.0 <4.0.0"


dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0

topics:
  - dropdown
  - search
  - form
  - material
  - adaptive
